CREATE LOGIN MyLogin WITH PASSWORD = '123';
GO
CREATE LOGIN GVPTLogin WITH PASSWORD = '123';
GO
CREATE LOGIN GVQLLogin WITH PASSWORD = '123';
GO
CREATE LOGIN SVLogin WITH PASSWORD = '123';
GO

USE Ass2
GO

create user Adm for login MyLogin;
GO
create user GVPTUser for login GVPTLogin;
GO
create user GVQLUser for login GVQLLogin;
GO
create user SVUser for login SVLogin;
GO

GRANT ALL ON CAU_HOI TO Adm; 
GRANT ALL ON CHUAN_DAU_RA TO Adm;
GRANT ALL ON DE_THI TO Adm;
GRANT ALL ON DE_THI_BAO_GOM_CAU_HOI TO Adm;
GRANT ALL ON FILE_MO_TA TO Adm;
GRANT ALL ON GIANG_VIEN_PHU_TRACH TO Adm;
GRANT ALL ON GIANG_VIEN_QUAN_LY TO Adm;
GRANT ALL ON LAM_BAI TO Adm;
GRANT ALL ON LAN_THI TO Adm;
GRANT ALL ON MON_HOC TO Adm;
GRANT ALL ON PCH_CHUA_FMT TO Adm;
GRANT ALL ON PMTC_CHUA_FMT TO Adm;
GRANT ALL ON PTL_CHUA_FMT TO Adm;
GRANT ALL ON PHAN_CAU_HOI TO Adm;
GRANT ALL ON PHAN_MO_TA_CHUNG TO Adm;
GRANT ALL ON PHAN_TRA_LOI TO Adm;
GRANT ALL ON SINH_VIEN TO Adm;
GRANT ALL ON TAP_DE_THI TO Adm;
GRANT ALL ON TAP_DE_THI_BAO_GOM_CAU_HOI TO Adm;

GRANT ALL ON GIANG_VIEN_PHU_TRACH TO GVPTUser;
GRANT ALL ON CAU_HOI TO GVPTUser; 
GRANT ALL ON PCH_CHUA_FMT TO GVPTUser;
GRANT ALL ON PMTC_CHUA_FMT TO GVPTUser;
GRANT ALL ON PTL_CHUA_FMT TO GVPTUser;
GRANT ALL ON PHAN_CAU_HOI TO GVPTUser;
GRANT ALL ON PHAN_MO_TA_CHUNG TO GVPTUser;
GRANT ALL ON PHAN_TRA_LOI TO GVPTUser;
GRANT ALL ON FILE_MO_TA TO GVPTUser;
GRANT ALL ON DE_THI TO GVPTUser;
GRANT ALL ON DE_THI_BAO_GOM_CAU_HOI TO GVPTUser;
GRANT ALL ON TAP_DE_THI TO GVPTUser;
GRANT ALL ON TAP_DE_THI_BAO_GOM_CAU_HOI TO GVPTUser;

GRANT ALL ON GIANG_VIEN_QUAN_LY TO GVQLUser;
GRANT ALL ON CAU_HOI TO GVQLUser; 
GRANT ALL ON PCH_CHUA_FMT TO GVQLUser;
GRANT ALL ON PMTC_CHUA_FMT TO GVQLUser;
GRANT ALL ON PTL_CHUA_FMT TO GVQLUser;
GRANT ALL ON PHAN_CAU_HOI TO GVQLUser;
GRANT ALL ON PHAN_MO_TA_CHUNG TO GVQLUser;
GRANT ALL ON PHAN_TRA_LOI TO GVQLUser;
GRANT ALL ON FILE_MO_TA TO GVQLUser;
GRANT ALL ON DE_THI TO GVQLUser;
GRANT ALL ON DE_THI_BAO_GOM_CAU_HOI TO GVQLUser;
GRANT ALL ON TAP_DE_THI TO GVQLUser;
GRANT ALL ON TAP_DE_THI_BAO_GOM_CAU_HOI TO GVQLUser;

GRANT ALL ON LAM_BAI TO SVUser;
GRANT ALL ON SINH_VIEN TO SVUser;



