CREATE LOGIN MyLogin WITH PASSWORD = '123';
GO
CREATE LOGIN GVPTLogin WITH PASSWORD = '123';
GO
CREATE LOGIN GVQLLogin WITH PASSWORD = '123';
GO
CREATE LOGIN SVLogin WITH PASSWORD = '123';
GO

USE Ass2
GO

create user Adm for login MyLogin;
GO
create user GVPTUser for login GVPTLogin;
GO
create user GVQLUser for login GVQLLogin;
GO
create user SVUser for login SVLogin;
GO


GRANT SELECT,UPDATE,INSERT,DELETE ON DATABASE :: Ass2 TO Adm
GO

GRANT EXECUTE ON dbo.PassGVPT TO [Adm];
GRANT EXECUTE ON dbo.PassGVQL TO [Adm];
GRANT EXECUTE ON dbo.PassSV TO [Adm];
GRANT EXECUTE ON dbo.checkLamBai TO [Adm];
GRANT EXECUTE ON dbo.setUpLamBai TO [Adm];
GO

GRANT ALL ON CAU_HOI TO GVPTUser; 
GRANT ALL ON PCH_CHUA_FMT TO GVPTUser;
GRANT ALL ON PMTC_CHUA_FMT TO GVPTUser;
GRANT ALL ON PTL_CHUA_FMT TO GVPTUser;
GRANT ALL ON PHAN_CAU_HOI TO GVPTUser;
GRANT ALL ON PHAN_MO_TA_CHUNG TO GVPTUser;
GRANT ALL ON PHAN_TRA_LOI TO GVPTUser;
GRANT ALL ON FILE_MO_TA TO GVPTUser;
GRANT ALL ON DE_THI TO GVPTUser;
GRANT ALL ON DE_THI_BAO_GOM_CAU_HOI TO GVPTUser;
GRANT ALL ON TAP_DE_THI TO GVPTUser;
GRANT ALL ON TAP_DE_THI_BAO_GOM_CAU_HOI TO GVPTUser;
GRANT EXECUTE ON dbo.PassGVPT TO [GVPTUser];

GRANT SELECT ON i4 TO [GVPTUser];
GRANT SELECT ON i5 TO [GVPTUser];
GRANT EXECUTE ON i6d TO [GVPTUser];
GRANT SELECT ON i6 TO [GVPTUser];
GRANT EXECUTE ON i7d TO [GVPTUser];
GRANT EXECUTE ON i7s TO [GVPTUser];
GRANT SELECT ON CDRi8 TO [GVPTUser];
GRANT SELECT ON CHi8 TO [GVPTUser];
GRANT EXECUTE ON CHi8d TO [GVPTUser];
GRANT EXECUTE ON CHi8t TO [GVPTUser];
GRANT SELECT ON i8 TO [GVPTUser];
GRANT SELECT ON i9 TO [GVPTUser];
GRANT SELECT ON i10 TO [GVPTUser];
GRANT EXECUTE ON i12 TO [GVPTUser];
GO

GRANT ALL ON CAU_HOI TO GVQLUser; 
GRANT ALL ON PCH_CHUA_FMT TO GVQLUser;
GRANT ALL ON PMTC_CHUA_FMT TO GVQLUser;
GRANT ALL ON PTL_CHUA_FMT TO GVQLUser;
GRANT ALL ON PHAN_CAU_HOI TO GVQLUser;
GRANT ALL ON PHAN_MO_TA_CHUNG TO GVQLUser;
GRANT ALL ON PHAN_TRA_LOI TO GVQLUser;
GRANT ALL ON FILE_MO_TA TO GVQLUser;
GRANT ALL ON DE_THI TO GVQLUser;
GRANT ALL ON DE_THI_BAO_GOM_CAU_HOI TO GVQLUser;
GRANT ALL ON TAP_DE_THI TO GVQLUser;
GRANT ALL ON TAP_DE_THI_BAO_GOM_CAU_HOI TO GVQLUser;
GRANT EXECUTE ON dbo.PassGVQL TO [GVQLUser];

GRANT EXECUTE ON i6d TO [GVQLUser];
GRANT SELECT ON i6 TO [GVQLUser];
GRANT EXECUTE ON i7d TO [GVQLUser];
GRANT EXECUTE ON i7s TO [GVQLUser];
GRANT SELECT ON CDRi8 TO [GVQLUser];
GRANT SELECT ON CHi8 TO [GVQLUser];
GRANT EXECUTE ON CHi8d TO [GVQLUser];
GRANT EXECUTE ON CHi8t TO [GVQLUser];
GRANT SELECT ON i8 TO [GVQLUser];
GRANT SELECT ON i9 TO [GVQLUser];
GRANT SELECT ON i10 TO [GVQLUser];
GRANT EXECUTE ON i12 TO [GVQLUser];
GRANT SELECT ON ii10all TO [GVQLUser];
GRANT SELECT ON ii10 TO [GVQLUser];
GO

GRANT ALL ON LAM_BAI TO SVUser;
GRANT ALL ON NOTE TO SVUser;
GRANT EXECUTE ON dbo.PassSV TO [SVUser];
GRANT EXECUTE ON dbo.setUpLamBai TO [SVUser];

GRANT SELECT ON iii3 TO [SVUser];
GRANT SELECT ON iii4 TO [SVUser];
GRANT SELECT ON iii5 TO [SVUser];
GRANT SELECT ON iii6 TO [SVUser];
GRANT SELECT ON iii7 TO [SVUser];
GO



