USE Ass2
GO

CREATE OR ALTER PROCEDURE i12 @MCH AS varchar(10)
AS
BEGIN
	TRUNCATE TABLE ti12
	DECLARE @MyCursor CURSOR;
	DECLARE @MyField INT;
	BEGIN
    SET @MyCursor = CURSOR FOR
    SELECT TOP(3) D.Trich_Lan_thi FROM DE_THI AS D WHERE Trich_Mon_hoc = @MCH ORDER BY Trich_Lan_thi ASC    

    OPEN @MyCursor 
    FETCH NEXT FROM @MyCursor 
    INTO @MyField

    WHILE @@FETCH_STATUS = 0
    BEGIN
		INSERT INTO ti12 SELECT TOP(1) WITH TIES * FROM i8 ('CO2012', @MyField) ORDER BY Ratio ASC
		FETCH NEXT FROM @MyCursor 
		INTO @MyField 
    END; 

    CLOSE @MyCursor ;
    DEALLOCATE @MyCursor;
	END;
END;
GO

EXEC i12 @MCH = 'CO2012';
SELECT * FROM ti12

