CREATE OR ALTER PROCEDURE xoaCauhoi @MCH AS varchar(10)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM TAP_DE_THI_BAO_GOM_CAU_HOI WHERE Ma_cau_hoi = @MCH) AND NOT EXISTS(SELECT * FROM DE_THI_BAO_GOM_CAU_HOI WHERE Ma_cau_hoi = @MCH)
	BEGIN
		DELETE FROM PTL_CHUA_FMT WHERE Ma_cau_hoi = @MCH;
		DELETE FROM PHAN_TRA_LOI WHERE Ma_cau_hoi = @MCH;
		DELETE FROM PCH_CHUA_FMT WHERE Ma_cau_hoi = @MCH;
		DELETE FROM PHAN_CAU_HOI WHERE Ma_cau_hoi = @MCH;
		DELETE FROM CAU_HOI WHERE Ma_cau_hoi = @MCH;
	END;
END;
GO

CREATE OR ALTER FUNCTION tatcaCauhoi (@MH AS varchar(10))
RETURNS TABLE AS
RETURN
	SELECT C.Ma_cau_hoi, Noi_dung, Vi_tri_dap_an_dung, STTCDR, ID_phan_mo_ta 
	FROM CAU_HOI AS C JOIN PHAN_CAU_HOI AS P ON C.Ma_cau_hoi = P.Ma_cau_hoi
	WHERE Ma_mon_hoc_thuoc = @MH
GO

CREATE OR ALTER FUNCTION thongtinCauhoi (@MH AS varchar(10))
RETURNS TABLE AS
RETURN
	SELECT *
	FROM CAU_HOI
GO

